[phases.install]
cmds = ["corepack enable", "corepack prepare pnpm@9.15.1 --activate", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm prisma:generate", "pnpm build"]

[variables]
PORT = "3000"
NODE_ENV = "production"
NIXPACKS_BUILD_CMD = "pnpm build"

[start]
cmd = "pnpm start"
